config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'paragraphs#index'

  get '/admin', to: 'dashboard/offers#index'

  resources :paragraphs, only: [:index], path: 'about'
  resources :details,    only: [:index]
  resources :offers,     only: [:index]

  resources :members,    only: %i[index show], param: :slug
  resources :bookings,   only: %i[new index]

  namespace :dashboard do
    resources :members,    except: [:show]
    resources :offers,     except: [:show]
    resources :paragraphs, except: [:show]

    resources :bookings do
      resources :approvals, only: :create
    end

    resources :bookings, param: :year do
      resources :weeks, param: :week_number, controller: 'bookings/weeks'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :offers, only: [:index]
      resources :bookings, only: [:create]
      resources :reservation_dates, only: [:index]
    end
  end
end

app/models/member.rb
# The model Member holds the public profile data of staff members.
class Member < ApplicationRecord
  has_many :offers

  has_attached_file(
    :avatar,
    styles: { medium: '300x300>', thumb: '100x100>' },
    default_url: '/images/:style/missing.png'
  )

  has_many :reservations
  has_many :bookings, through: :reservations

  before_validation :generate_slug, on: :create

  validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\Z}

  validates_presence_of :first_name,
                        :last_name,
                        :profession,
                        :description

  validates :slug, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def generate_slug
    self.slug = SecureRandom.hex
  end
end

app/controllers/dashboard/admin_controller.rb
module Dashboard
  class AdminController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_user!
  end
end

app/controllers/dashboard/bookings/weeks_controller.rb
require_dependency './app/queries/bookings_by_weeks'

module Dashboard
  module Bookings
    class WeeksController < AdminController
      def show
        week = params[:week_number]
        year = params[:booking_year]

        @bookings = ::Queries::BookingsByWeeks.where(week: week, year: year)
      end
    end
  end
end

app/controllers/dashboard/bookings_controller.rb
module Dashboard
  # :nodoc:
  class BookingsController < AdminController
    def index
      @confirmed = Booking.confirmed.desc_order
      @pending = Booking.pending.desc_order
    end

    def show
      @booking = Booking.find(params[:id])
    end
  end
end

app/controllers/dashboard/members_controller.rb
module Dashboard
  # :nodoc:
  class MembersController < AdminController
    include Memberable
    before_action :find_member, only: %i[update edit destroy]

    def new
      @member = Member.new
    end

    def create
      @member = Member.new(member_params)

      if @member.save
        redirect_to dashboard_members_path, notice: t(:created_successfully)
      else
        render :new
        flash[:error] = t(:something_went_wrong)
      end
    end

    def edit; end

    def update
      if @member.update(member_params)
        redirect_to dashboard_members_path, notice: t(:updated_successfully)
      else
        render :edit
        flash[:error] = t(:something_went_wrong)
      end
    end

    def destroy
      @member.destroy!
      redirect_to dashboard_members_path, notice: t(:record_deleted)
    end

    private

    def find_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(
        :first_name,
        :last_name,
        :profession,
        :description,
        :phone_number,
        :avatar
      )
    end
  end
end

app/controllers/dashboard/offers_controller.rb
module Dashboard
  # :nodoc:
  class OffersController < AdminController
    include Offerable

    before_action :find_offer, only: %i[update edit destroy]

    def new
      @offer = Offer.new
    end

    def create
      @offer = Offer.new(offer_params)

      if @offer.save
        redirect_to dashboard_offers_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:new)
      end
    end

    def edit; end

    def update
      if @offer.update(offer_params)
        redirect_to dashboard_offers_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:edit)
      end
    end

    def destroy
      @offer.destroy!
      redirect_to dashboard_offers_path, notice: t(:record_deleted)
    end

    private

    def find_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:description, :name, :price, :member_id)
    end
  end
end

app/controllers/dashboard/paragraphs_controller.rb
module Dashboard
  # :nodoc:
  class ParagraphsController < AdminController
    include Paragraphable
    before_action :find_paragraph, only: %i[update edit destroy]

    def new
      @paragraph = Paragraph.new
    end

    def create
      @paragraph = Paragraph.new(paragraph_params)

      if @paragraph.save
        redirect_to dashboard_paragraphs_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :new
      end
    end

    def edit; end

    def update
      if @paragraph.update(paragraph_params)
        redirect_to dashboard_paragraphs_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :edit
      end
    end

    def destroy
      @paragraph.destroy!
      redirect_to dashboard_paragraphs_path, notice: t(:record_deleted)
    end

    private

    def find_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    def paragraph_params
      params.require(:paragraph).permit(:id, :title, :body)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include Memberable

  def show
    @member = Member.find_by(slug: params[:slug])
  end
end

app/views/dashboard/members/_form.html.erb
<%= form_for [:dashboard, @member] do |f| %>
    <div class='form-group'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :profession %>
    <%= f.text_field :profession, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.file_field :avatar %>
  </div>

  <div class='form-group'>
    <%= f.submit t(:submit), class: 'btn btn-warning btn-lg' %>
  </div>
<% end %>

app/views/dashboard/members/_member.html.erb
<%#= image_tag(member.avatar(:thumb)) %>

<h4><%= member.full_name %></h4>
<p><%= member.profession %></p>
<p><%= member.phone_number %></p>

<p><%= member.description %></p>

<li>Created:<%= member.created_at.to_formatted_s(:long_ordinal) %></li>
<li>Updated:<%= member.updated_at.to_formatted_s(:long_ordinal) %></li>

<%= link_to t(:edit), edit_dashboard_member_path(member), class: 'btn btn-warning btn-sx' %>

<%= link_to t(:remove), dashboard_member_path(member), method: :delete,
                                                       data: { confirm: 'Are you sure?' },
                                                       class: 'btn btn-danger btn-sx' %>

app/views/dashboard/members/edit.html.erb
<div class='row'>
  <h4><%= t(:edit_member) %></h4>
  <%= render 'form' %>
</div>

app/views/dashboard/members/index.html.erb
<div class='row'>
  <%= link_to t(:new), new_dashboard_member_path, class: 'btn btn-success btn-lg' %>
  <%= link_to t(:public_area), members_path, class: 'btn btn-success btn-lg' %>
</div>

<%= render @members %>

app/views/dashboard/members/new.html.erb
<div class='row'>
  <h4><%= t(:new_member) %></h4>
  <%= render 'form' %>
</div>