config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'paragraphs#index'

  get '/admin', to: 'dashboard/offers#index'

  resources :paragraphs, only: [:index], path: 'about'
  resources :details,    only: [:index]
  resources :offers,     only: [:index]

  resources :members,    only: %i[index show], param: :slug
  resources :bookings,   only: %i[new index]

  namespace :dashboard do
    resources :members,    except: [:show]
    resources :offers,     except: [:show]
    resources :paragraphs, except: [:show]

    resources :bookings do
      resources :approvals, only: :create
    end

    resources :bookings, param: :year do
      resources :weeks, param: :week_number, controller: 'bookings/weeks'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :offers, only: [:index]
      resources :bookings, only: [:create]
      resources :reservation_dates, only: [:index]
    end
  end
end

app/models/booking.rb
# Booking model is designed to be created by either a user
# or an admin (from the admin panel)
class Booking < ApplicationRecord
  belongs_to :offer

  validates :reserved_at, presence: true
  validates :week_number, presence: true

  scope :confirmed, -> { where(confirmed: true) }
  scope :pending, -> { where(confirmed: false) }
  scope :desc_order, -> { order('bookings.reserved_at DESC') }

  scope :by_year, ->(year) { where('extract(year from bookings.reserved_at) = ?', year) }
  scope :by_week, ->(week, year) { where(week_number: week).by_year(year) }

  before_validation on: :create do
    self.week_number = reserved_at&.strftime('%W')
  end
end

app/controllers/api/v1/bookings_controller.rb
module Api
  module V1
    class BookingsController < ApiController
      def create
        @booking = Booking.new(booking_params)

        if @booking.save
          render json: { success: 'Reservation saved!' }, status: 200
        else
          errors = @booking.errors.full_messages.to_sentence
          render json: { error: errors }, status: 422
        end
      end

      private

      def booking_params
        params.require(:booking).permit(
          :first_name,
          :last_name,
          :additional_info,
          :phone,
          :reserved_at,
          :offer_id
        )
      end
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    redirect_to new_booking_path
  end

  def new; end
end

app/controllers/dashboard/admin_controller.rb
module Dashboard
  class AdminController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_user!
  end
end

app/controllers/dashboard/bookings/weeks_controller.rb
require_dependency './app/queries/bookings_by_weeks'

module Dashboard
  module Bookings
    class WeeksController < AdminController
      def show
        week = params[:week_number]
        year = params[:booking_year]

        @bookings = ::Queries::BookingsByWeeks.where(week: week, year: year)
      end
    end
  end
end

app/controllers/dashboard/bookings_controller.rb
module Dashboard
  # :nodoc:
  class BookingsController < AdminController
    def index
      @confirmed = Booking.confirmed.desc_order
      @pending = Booking.pending.desc_order
    end

    def show
      @booking = Booking.find(params[:id])
    end
  end
end

app/controllers/dashboard/members_controller.rb
module Dashboard
  # :nodoc:
  class MembersController < AdminController
    include Memberable
    before_action :find_member, only: %i[update edit destroy]

    def new
      @member = Member.new
    end

    def create
      @member = Member.new(member_params)

      if @member.save
        redirect_to dashboard_members_path, notice: t(:created_successfully)
      else
        render :new
        flash[:error] = t(:something_went_wrong)
      end
    end

    def edit; end

    def update
      if @member.update(member_params)
        redirect_to dashboard_members_path, notice: t(:updated_successfully)
      else
        render :edit
        flash[:error] = t(:something_went_wrong)
      end
    end

    def destroy
      @member.destroy!
      redirect_to dashboard_members_path, notice: t(:record_deleted)
    end

    private

    def find_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(
        :first_name,
        :last_name,
        :profession,
        :description,
        :phone_number,
        :avatar
      )
    end
  end
end

app/controllers/dashboard/offers_controller.rb
module Dashboard
  # :nodoc:
  class OffersController < AdminController
    include Offerable

    before_action :find_offer, only: %i[update edit destroy]

    def new
      @offer = Offer.new
    end

    def create
      @offer = Offer.new(offer_params)

      if @offer.save
        redirect_to dashboard_offers_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:new)
      end
    end

    def edit; end

    def update
      if @offer.update(offer_params)
        redirect_to dashboard_offers_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:edit)
      end
    end

    def destroy
      @offer.destroy!
      redirect_to dashboard_offers_path, notice: t(:record_deleted)
    end

    private

    def find_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:description, :name, :price, :member_id)
    end
  end
end

app/controllers/dashboard/paragraphs_controller.rb
module Dashboard
  # :nodoc:
  class ParagraphsController < AdminController
    include Paragraphable
    before_action :find_paragraph, only: %i[update edit destroy]

    def new
      @paragraph = Paragraph.new
    end

    def create
      @paragraph = Paragraph.new(paragraph_params)

      if @paragraph.save
        redirect_to dashboard_paragraphs_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :new
      end
    end

    def edit; end

    def update
      if @paragraph.update(paragraph_params)
        redirect_to dashboard_paragraphs_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :edit
      end
    end

    def destroy
      @paragraph.destroy!
      redirect_to dashboard_paragraphs_path, notice: t(:record_deleted)
    end

    private

    def find_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    def paragraph_params
      params.require(:paragraph).permit(:id, :title, :body)
    end
  end
end

app/views/dashboard/bookings/_booking.html.erb
<div class='col-lg-4'>
  <div class='well'>
    <h5><%= full_name(booking) %></h5>
    <small><%= booking.phone %></small>
    <p><%= t(:approved) %>: <%= booking.approved %></p>
    <%= link_to 'View', dashboard_booking_path(booking), class: 'btn btn-warning btn-xs' %>
  </div>
</div>

app/views/dashboard/bookings/index.html.erb
<h4><%= t(:all_reservations) %></h4>

<%= react_component 'BookingsBoard', { confirmed: @confirmed, pending: @pending } %>

app/views/dashboard/bookings/show.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <div class="btn-group btn-group-justified" role="group" aria-label="...">

    <%= link_to 'Previous', '#', class: 'btn btn-warning btn-sx' %>

    <%= approve_path %>

    <%= link_to 'Next', '#', class: 'btn btn-warning btn-sx' %>
    </div>

    <div class='well'>
      <table class='table'>
        <tr>
          <th>First Name</th>
          <td><%= @booking.first_name %></td>
        </tr>
        <tr>
          <th>Last Name</th>
          <td><%= @booking.last_name %></td>
        </tr>
        <tr>
          <th>Phone</th>
          <td><%= @booking.phone %></td>
        </tr>
        <tr>
          <th>Reserved At</th>
          <td><%= @booking.reserved_at %></td>
        </tr>
        <tr>
          <th>Confirmed</th>
          <td><h4><span class="label label-info"><%= @booking.confirmed %></span></h4></td>
        </tr>
        <tr>
          <th>Booking ID</th>
          <td><%= @booking.id %></td>
        </tr>
        <tr>
          <th>Additional Info</th>
          <td><%= @booking.additional_info %></td>
        </tr>
      </table>
    </div>
  </div>
</div>