config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'paragraphs#index'

  get '/admin', to: 'dashboard/offers#index'

  resources :paragraphs, only: [:index], path: 'about'
  resources :details,    only: [:index]
  resources :offers,     only: [:index]

  resources :members,    only: %i[index show], param: :slug
  resources :bookings,   only: %i[new index]

  namespace :dashboard do
    resources :members,    except: [:show]
    resources :offers,     except: [:show]
    resources :paragraphs, except: [:show]

    resources :bookings do
      resources :approvals, only: :create
    end

    resources :bookings, param: :year do
      resources :weeks, param: :week_number, controller: 'bookings/weeks'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :offers, only: [:index]
      resources :bookings, only: [:create]
      resources :reservation_dates, only: [:index]
    end
  end
end

app/models/offer.rb
# Represents a bookable offer which is available in the salon.
class Offer < ApplicationRecord
  belongs_to :member

  has_many :bookings

  validates :description, presence: true
  validates :name,        presence: true

  delegate :slug,      to: :member, prefix: true
  delegate :full_name, to: :member, prefix: true

  def to_s
    "#{price} - #{name}"
  end
end

app/controllers/api/v1/offers_controller.rb
require_dependency './app/queries/offer_member'

module Api
  module V1
    # :nodoc:
    class OffersController < ApiController
      def index
        render json: ::Queries::OfferMember.all
      end
    end
  end
end

app/controllers/dashboard/admin_controller.rb
module Dashboard
  class AdminController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_user!
  end
end

app/controllers/dashboard/bookings/weeks_controller.rb
require_dependency './app/queries/bookings_by_weeks'

module Dashboard
  module Bookings
    class WeeksController < AdminController
      def show
        week = params[:week_number]
        year = params[:booking_year]

        @bookings = ::Queries::BookingsByWeeks.where(week: week, year: year)
      end
    end
  end
end

app/controllers/dashboard/bookings_controller.rb
module Dashboard
  # :nodoc:
  class BookingsController < AdminController
    def index
      @confirmed = Booking.confirmed.desc_order
      @pending = Booking.pending.desc_order
    end

    def show
      @booking = Booking.find(params[:id])
    end
  end
end

app/controllers/dashboard/members_controller.rb
module Dashboard
  # :nodoc:
  class MembersController < AdminController
    include Memberable
    before_action :find_member, only: %i[update edit destroy]

    def new
      @member = Member.new
    end

    def create
      @member = Member.new(member_params)

      if @member.save
        redirect_to dashboard_members_path, notice: t(:created_successfully)
      else
        render :new
        flash[:error] = t(:something_went_wrong)
      end
    end

    def edit; end

    def update
      if @member.update(member_params)
        redirect_to dashboard_members_path, notice: t(:updated_successfully)
      else
        render :edit
        flash[:error] = t(:something_went_wrong)
      end
    end

    def destroy
      @member.destroy!
      redirect_to dashboard_members_path, notice: t(:record_deleted)
    end

    private

    def find_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(
        :first_name,
        :last_name,
        :profession,
        :description,
        :phone_number,
        :avatar
      )
    end
  end
end

app/controllers/dashboard/offers_controller.rb
module Dashboard
  # :nodoc:
  class OffersController < AdminController
    include Offerable

    before_action :find_offer, only: %i[update edit destroy]

    def new
      @offer = Offer.new
    end

    def create
      @offer = Offer.new(offer_params)

      if @offer.save
        redirect_to dashboard_offers_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:new)
      end
    end

    def edit; end

    def update
      if @offer.update(offer_params)
        redirect_to dashboard_offers_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render(:edit)
      end
    end

    def destroy
      @offer.destroy!
      redirect_to dashboard_offers_path, notice: t(:record_deleted)
    end

    private

    def find_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(:description, :name, :price, :member_id)
    end
  end
end

app/controllers/dashboard/paragraphs_controller.rb
module Dashboard
  # :nodoc:
  class ParagraphsController < AdminController
    include Paragraphable
    before_action :find_paragraph, only: %i[update edit destroy]

    def new
      @paragraph = Paragraph.new
    end

    def create
      @paragraph = Paragraph.new(paragraph_params)

      if @paragraph.save
        redirect_to dashboard_paragraphs_path, notice: t(:created_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :new
      end
    end

    def edit; end

    def update
      if @paragraph.update(paragraph_params)
        redirect_to dashboard_paragraphs_path, notice: t(:updated_successfully)
      else
        flash[:error] = t(:something_went_wrong)
        render :edit
      end
    end

    def destroy
      @paragraph.destroy!
      redirect_to dashboard_paragraphs_path, notice: t(:record_deleted)
    end

    private

    def find_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    def paragraph_params
      params.require(:paragraph).permit(:id, :title, :body)
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.includes(:member)
  end
end

app/helpers/offers_helper.rb
# :nodoc:
module OffersHelper
  def format_price(offer)
    '%.2f BGN' % offer.price
  end

  def selection_tuples
    Member.all.map { |m| [m.full_name, m.id] }
  end
end

app/views/dashboard/offers/_form.html.erb
<%= form_for [:dashboard, @offer] do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :member %>
    <%= f.select :member_id, selection_tuples, {}, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.submit t(:submit), class: 'btn btn-warning btn-lg' %>
  </div>
<% end %>

app/views/dashboard/offers/_offer.html.erb
<div class='col-lg-12'>
  <h4><%= offer.name %></h4>
  <p><%= offer.description %></p>

  <ul>
    <li>Price: <%= "#{offer.price} лв" %></li>
    <li>Created: <%= offer.created_at.to_formatted_s(:long_ordinal) %></li>
    <li>Updated: <%= offer.updated_at.to_formatted_s(:long_ordinal) %></li>
  </ul>

  <%= link_to t(:edit), edit_dashboard_offer_path(offer),
                        class: 'btn btn-warning btn-sx' %>

  <%= link_to t(:remove), dashboard_offer_path(offer), method: :delete,
                                                       data: { confirm: 'Are you sure?' },
                                                       class: 'btn btn-danger btn-sx' %>
</div>

app/views/dashboard/offers/edit.html.erb
<div class='row'>
  <h4><%= t(:edit_offer) %></h4>
  <%= render 'form' %>
</div>

app/views/dashboard/offers/index.html.erb
<div class='row'>
  <%= link_to t(:new), new_dashboard_offer_path, class: 'btn btn-success btn-lg' %>
  <%= link_to t(:public_area), offers_path, class: 'btn btn-success btn-lg' %>
</div>

<div class='row'>
  <%= render @offers %>
</div>

app/views/dashboard/offers/new.html.erb
<div class='row'>
  <h4><%= t(:new_offer) %></h4>
  <%= render 'form' %>
</div>